apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: lseg
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: svc-v1
                port:
                  number: 80
      host: v1.app.avi.com